#!/bin/sh
set -e
# Read more info at: https://medium.com/@alistair.cerio/android-ktlint-and-pre-commit-git-hook-5dd606e230a9

echo "***************************"
echo "Running git pre-commit hook"
echo "***************************"

# Run afs_ktlint to make sure there is no lint issue
./gradlew afs_ktlint

RESULT=$?

# return 1 exit code if running checks fails
[[ ${RESULT} -ne 0 ]] && exit 1
  exit 0

exit 0